# Generated by Django 3.0 on 2019-12-13 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_category', models.CharField(max_length=200)),
                ('note_summary', models.CharField(max_length=200)),
                ('note_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='NoteSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('note_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.NoteCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=250)),
                ('note_content', models.TextField(default='')),
                ('note_published', models.DateTimeField(default=datetime.datetime(2019, 12, 13, 12, 12, 35, 905358, tzinfo=utc), verbose_name='date published')),
                ('note_slug', models.CharField(default=1, max_length=200)),
                ('note_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.NoteSeries', verbose_name='Series')),
            ],
        ),
    ]
