# Generated by Django 3.0 on 2019-12-13 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notecategory',
            old_name='note_summary',
            new_name='category_summary',
        ),
        migrations.AlterField(
            model_name='note',
            name='note_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 12, 42, 37, 814891, tzinfo=utc), verbose_name='date published'),
        ),
    ]
