# Generated by Django 3.0 on 2019-12-13 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191213_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notecategory',
            old_name='note_slug',
            new_name='category_slug',
        ),
        migrations.AlterField(
            model_name='note',
            name='note_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 12, 43, 51, 779180, tzinfo=utc), verbose_name='date published'),
        ),
    ]
