# Generated by Django 3.0 on 2019-12-13 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191213_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='notecategory',
            name='category_image',
            field=models.CharField(default='main/images/classwork.jpeg', max_length=200),
        ),
        migrations.AddField(
            model_name='noteseries',
            name='series_image',
            field=models.TextField(default='https://source.unsplash.com/random'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 15, 47, 54, 437640, tzinfo=utc), verbose_name='date published'),
        ),
    ]
