# Generated by Django 3.0 on 2019-12-13 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191213_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 16, 30, 12, 95655, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='notecategory',
            name='category_image',
            field=models.CharField(default='classwork.jpeg', max_length=200),
        ),
    ]
