# Generated by Django 3.0 on 2019-12-15 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20191215_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 16, 59, 43, 775204, tzinfo=utc), verbose_name='date published'),
        ),
    ]
