# Generated by Django 3.0 on 2019-12-16 06:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191215_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 6, 21, 59, 980297, tzinfo=utc), verbose_name='date published'),
        ),
    ]
