# Generated by Django 3.0 on 2019-12-27 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191216_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 6, 9, 40, 576850, tzinfo=utc), verbose_name='date published'),
        ),
    ]
